name: Pull Request Close
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  on_pr_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR was merged into main"
