name: Pull Request Open
on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  run_if:
    if: startsWith(github.head_ref, 'feature')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Feature branch PR opened against main"
